/**
 * Core provider interfaces — define the contracts that all AI provider
 * implementations (Faster-Whisper, Gemini, Ollama, Local LLM, etc.) must satisfy.
 *
 * Every interface is implementation-agnostic. Consumers depend only on
 * these contracts, never on concrete classes.
 */

import type { AppConfig } from '../config/index';

// ──────────────────────────────────────────────────────────────────────────────
// Common types shared across providers
// ──────────────────────────────────────────────────────────────────────────────

/** Confidence-scored word produced by speech recognition */
export interface TranscriptionWord {
  word: string;
  startTime: number; // seconds
  endTime: number; // seconds
  confidence: number; // 0-1
}

/** A contiguous segment of transcription output */
export interface TranscriptionSegment {
  id: number;
  text: string;
  startTime: number; // seconds
  endTime: number; // seconds
  words: TranscriptionWord[];
  confidence: number; // 0-1
  language?: string;
}

/** Complete transcription result from a speech-recognition provider */
export interface TranscriptionResult {
  segments: TranscriptionSegment[];
  fullText: string;
  language: string;
  durationSeconds: number;
  metadata: Record<string, unknown>;
}

/** A single chapter generated by an LLM */
export interface GeneratedChapter {
  index: number;
  title: string;
  summary: string;
  startTime: number; // seconds
  endTime: number; // seconds
  keywords: string[];
}

/** Complete chapter-generation result */
export interface ChapterGenerationResult {
  chapters: GeneratedChapter[];
  modelUsed: string;
  tokensUsed: number;
  processingTimeMs: number;
}

/** A dense vector embedding */
export interface EmbeddingResult {
  vector: number[];
  model: string;
  tokensUsed: number;
}

/** LLM completion request */
export interface LLMCompletionRequest {
  prompt: string;
  systemPrompt?: string;
  maxTokens?: number;
  temperature?: number;
  responseFormat?: 'text' | 'json';
}

/** LLM completion response */
export interface LLMCompletionResponse {
  content: string;
  model: string;
  tokensUsed: {
    prompt: number;
    completion: number;
    total: number;
  };
  finishReason: string;
}

// ──────────────────────────────────────────────────────────────────────────────
// Provider interfaces
// ──────────────────────────────────────────────────────────────────────────────

/** Speech-to-text provider */
export interface ISpeechRecognitionProvider {
  readonly name: string;
  transcribe(audioPath: string, language?: string): Promise<TranscriptionResult>;
  isAvailable(): Promise<boolean>;
}

/** Large Language Model provider */
export interface ILLMProvider {
  readonly name: string;
  complete(request: LLMCompletionRequest): Promise<LLMCompletionResponse>;
  isAvailable(): Promise<boolean>;
}

/** Embedding (vector) provider */
export interface IEmbeddingProvider {
  readonly name: string;
  embed(text: string): Promise<EmbeddingResult>;
  embedBatch(texts: string[]): Promise<EmbeddingResult[]>;
  isAvailable(): Promise<boolean>;
}

// ──────────────────────────────────────────────────────────────────────────────
// Service interfaces
// ──────────────────────────────────────────────────────────────────────────────

/** Speech recognition orchestration service */
export interface ISpeechRecognitionService {
  transcribe(audioPath: string, language?: string): Promise<TranscriptionResult>;
}

/** Transcript cleaning service */
export interface ITranscriptCleaningService {
  clean(rawText: string): string;
  cleanSegments(segments: TranscriptionSegment[]): TranscriptionSegment[];
}

/** Semantic chunking engine */
export interface ISemanticChunkingService {
  chunk(segments: TranscriptionSegment[]): TranscriptionSegment[][];
}

/** Prompt template engine */
export interface IPromptTemplateEngine {
  render(templateName: string, variables: Record<string, unknown>): string;
  registerTemplate(name: string, template: string): void;
  hasTemplate(name: string): boolean;
}

/** Chapter generation engine */
export interface IChapterGenerationService {
  generate(
    segments: TranscriptionSegment[][],
    videoTitle?: string,
  ): Promise<ChapterGenerationResult>;
}

/** Embedding engine */
export interface IEmbeddingService {
  embed(text: string): Promise<EmbeddingResult>;
  embedBatch(texts: string[]): Promise<EmbeddingResult[]>;
}

// ──────────────────────────────────────────────────────────────────────────────
// Repository interfaces (database-agnostic)
// ──────────────────────────────────────────────────────────────────────────────

/** Generic CRUD repository */
export interface IRepository<T, ID = string> {
  findById(id: ID): Promise<T | null>;
  findAll(filter?: Partial<T>): Promise<T[]>;
  create(entity: Omit<T, 'id' | 'createdAt' | 'updatedAt'>): Promise<T>;
  update(id: ID, data: Partial<T>): Promise<T | null>;
  delete(id: ID): Promise<boolean>;
  count(filter?: Partial<T>): Promise<number>;
}

// ──────────────────────────────────────────────────────────────────────────────
// Cache interface
// ──────────────────────────────────────────────────────────────────────────────

export interface ICacheService {
  get<T>(key: string): Promise<T | null>;
  set<T>(key: string, value: T, ttlSeconds?: number): Promise<void>;
  delete(key: string): Promise<boolean>;
  has(key: string): Promise<boolean>;
  clear(): Promise<void>;
}

// ──────────────────────────────────────────────────────────────────────────────
// Health check interface
// ──────────────────────────────────────────────────────────────────────────────

export interface HealthCheckResult {
  status: 'healthy' | 'degraded' | 'unhealthy';
  service: string;
  latencyMs: number;
  message?: string;
  timestamp: string;
}

export interface IHealthChecker {
  check(): Promise<HealthCheckResult>;
}

// ──────────────────────────────────────────────────────────────────────────────
// Metrics interface
// ──────────────────────────────────────────────────────────────────────────────

export interface IMetricsCollector {
  incrementCounter(name: string, labels?: Record<string, string>): void;
  observeHistogram(name: string, value: number, labels?: Record<string, string>): void;
  setGauge(name: string, value: number, labels?: Record<string, string>): void;
}

// ──────────────────────────────────────────────────────────────────────────────
// Plugin interface
// ──────────────────────────────────────────────────────────────────────────────

export interface IPipelinePlugin {
  readonly name: string;
  readonly version: string;
  initialize(config: AppConfig): Promise<void>;
  destroy(): Promise<void>;
}

// ──────────────────────────────────────────────────────────────────────────────
// Provider factory interface
// ──────────────────────────────────────────────────────────────────────────────

export interface IProviderFactory<T> {
  create(providerName: string): T;
  getAvailableProviders(): string[];
}
